### ISSUE TITLE
Allow get requests via CORS

### ISSUE THREAD

**Issue by NBKelly** [Project-NISEI/cobra#66]
Hi,

I'm working on a proof of concept stat gathering tool and would love to be able to scrape cobra pages every so often without needing to have a middle-man server.

An alternative would be API access for cobra, but that would be a bit more of an undertaking.

**Comment by NBKelly** [comment]
Having said that, I just looked at what the discord bot does and found out I could use the json endpoint :joy:

**Comment by haradan** [comment]
We'd need some approval process for allowing external domains to make CORS calls. Otherwise we'd open Cobra up to various attacks.

You'll only need CORS if you make your requests from a browser. If you hold the data somewhere else it'd probably be easier to limit the number of times you need to hit Cobra (since you're not relying on browser storage). If you do that you could make the request from there instead?

**Comment by NBKelly** [comment]
Yeah, I eventually figured out I could just use the json endpoint like the cobra bot on discord does. It was a mission finding that out though.
